config/routes.rb
Rails.application.routes.draw do

 

  # 顧客用
# URL /customers/sign_in ...


# 管理者用
# URL /admin/sign_in ...
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  namespace :admin do
    resources :items, only: [:index, :show, :create, :new, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_histories, only: [:show, :update]
    resources :order_history_details, only: [:update]

    get 'top'=>'homes#top'

  end

  scope module: :public do
    
    root to: "homes#top"
    get "home/about" => "homes#about"
    post 'orders/confirm'=>'orders#confirm'
    get 'orders/complete'=>'orders#complete'
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    patch 'customers/withdraw'=>'customers#withdraw'
    delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :destroy, :create, :update]
    resources :orders, only: [:index, :show, :create, :new]
    resources :addresses, only: [:index, :destroy, :create,  :edit, :update]

  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }


end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :addresses
         has_many :cart_items
         has_many :order_histories
         
  def status_text
     if is_deleted == false
        "有効"
     else
        "退会"
     end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
end

app/models/home.rb
class Home < ApplicationRecord
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many   :cart_items
  has_many   :order_history_details
  belongs_to :genre
  
  has_one_attached :image
  
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [100, 100]).processed
  end
  
  def status_text
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
        
  
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  
  belongs_to :customer
  has_many :order_history_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: { awaiting_payment: 0, payment_confirmation: 1, in_production: 2, dispatch_in_preparation: 3, already_shipped: 4 }

  

  
end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord

belongs_to :item
belongs_to :order_history

  def subtotal
    tax_included_price * quantity
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!, except: [:top,:about]


  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)



  end

  def edit
    @customer = Customer.find(params[:id])

  end


  def index
    @customers = Customer.all.page(params[:page]).per(10)


  end

  def show
    @customer = Customer.find(params[:id])


  end

  private

  def customer_params
    params.require(:customer).permit(:email, :first_name, :first_name_kana, :last_name, :last_name_kana, :postal_code, :address, :telephone_number,:is_deleted)


  end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!, except: [:top,:about]


  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)


  end

  def edit
    @genre =Genre.find(params[:id])

  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path

  end

  def index
    @genre=Genre.new
    @genres=Genre.all

  end

private

def genre_params
  params.require(:genre).permit(:name)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController


def top
    @order_histories = OrderHistory.all.page(params[:page]).per(10)
    @order_history_details = OrderHistoryDetail.all

end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!, except: [:top,:about]

  def new
     @item = Item.new
     @genres=Genre.all


  end

  def update
    @item =Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)


  end

  def edit
     @item =Item.find(params[:id])
     @genres=Genre.all

  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)


  end

  def index
    @items = Item.all.page(params[:page]).per(10)

  end

  def show
    @item=Item.find(params[:id])



  end

  private

  def item_params

    params.require(:item).permit(:genre_id, :price, :name, :introduction,:is_active, :image)
  end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def order_histories
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
   <div class="container">
     <%= @customer.first_name %>
     <%= @customer.last_name %>さんの会員情報編集
     <div class="row pt-4">
       <div class="col">
         会員ID 
       </div>
       <div class="col">
         <%= @customer.id %>

       </div>
     </div>
     
     <%= form_with model: @customer,url: admin_customer_path,method: :patch do |f| %>
     
     <div class="row pt-4">
       <div class="col">
         <%= f.label :名前 %>
       </div>
       <div class="col">
         <%= f.text_field :first_name %>
         <%= f.text_field :last_name %>
       </div>
     </div>
     <div class="row pt-4">
       <div class="col">
         <%= f.label :フリガナ %>
       </div>
       <div class="col">
         <%= f.text_field :first_name_kana %>
         <%= f.text_field :last_name_kana %>
       </div>
     </div>
     <div class="row pt-4">
       <div class="col">
         <%= f.label :郵便番号 %>
       </div>
       <div class="col">
         <%= f.text_field :postal_code %>
       </div>
     </div>
     <div class="row pt-4">
       <div class="col">
         <%= f.label :住所 %>
       </div>
       <div class="col">
         <%= f.text_field :address %>
       </div>
     </div>
     <div class="row pt-4">
       <div class="col">
         <%= f.label :電話番号 %>
       </div>
       <div class="col">
         <%= f.text_field :telephone_number %>
       </div>
     </div>
     <div class="row pt-4">
       <div class="col">
         <%= f.label :メールアドレス %>
       </div>
       <div class="col">
         <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
       </div>
     </div>
     <div class="row pt-4">
       <div class="col">
         会員ステータス 
       </div>
       <div class="col">
         <%= f.radio_button :is_deleted,false %>有効
         <%= f.radio_button :is_deleted,true %>退会
       </div>
     </div>
     <div class="row pt-4">
       <div class="col text-center">
         <%= f.submit '変更を保存' %>
       </div>
       <% end %>
     </div>
   </div>

app/views/admin/customers/index.html.erb
<div class="container">

  <h1>会員一覧</h1>

  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <% @customers.each do |customer| %>

        <tbody>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.first_name %>
              <%= customer.last_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted==false %>
              有効
              <% else %>
              退会
              <% end %>
            </td>
          </tr>
        </tbody>

        <% end %>

      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-2 offset-5">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  
  <%= @customer.first_name %>
  <%= @customer.last_name %>さんの会員詳細

  <div class="row pt-3">
    <div class="col text-center">
      会員ID
    </div>
    <div class="col">
      <%= @customer.id%>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      氏名
    </div>
    <div class="col">
      <%= @customer.last_name %>
      <%= @customer.first_name %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      フリガナ
    </div>
    <div class="col">
      <%= @customer.last_name_kana %>
      <%= @customer.first_name_kana %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      郵便番号
    </div>
    <div class="col">
      <%= @customer.postal_code %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      住所
    </div>
    <div class="col">
      <%= @customer.address%>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      電話番号
    </div>
    <div class="col">
      <%= @customer.telephone_number %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      メールアドレス
    </div>
    <div class="col">
      <%= @customer.email %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      会員ステータス
    </div>
    <div class="col">
      <% if @customer.is_deleted==false %>
      有効
      <% else %>
      退会
      <% end %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success" %>
    </div>
    <div class="col">
      <%= link_to "注文履歴一覧", admin_top_path(@customer.id),class:"btn btn-primary" %>
    </div>
  </div>

</div>