config/routes.rb
Rails.application.routes.draw do

 

  # 顧客用
# URL /customers/sign_in ...


# 管理者用
# URL /admin/sign_in ...
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  namespace :admin do
    resources :items, only: [:index, :show, :create, :new, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_histories, only: [:show, :update]
    resources :order_history_details, only: [:update]

    get 'top'=>'homes#top'

  end

  scope module: :public do
    
    root to: "homes#top"
    get "home/about" => "homes#about"
    post 'orders/confirm'=>'orders#confirm'
    get 'orders/complete'=>'orders#complete'
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    patch 'customers/withdraw'=>'customers#withdraw'
    delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :destroy, :create, :update]
    resources :orders, only: [:index, :show, :create, :new]
    resources :addresses, only: [:index, :destroy, :create,  :edit, :update]

  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }


end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :addresses
         has_many :cart_items
         has_many :order_histories
         
  def status_text
     if is_deleted == false
        "有効"
     else
        "退会"
     end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
end

app/models/home.rb
class Home < ApplicationRecord
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many   :cart_items
  has_many   :order_history_details
  belongs_to :genre
  
  has_one_attached :image
  
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [100, 100]).processed
  end
  
  def status_text
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
        
  
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  
  belongs_to :customer
  has_many :order_history_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: { awaiting_payment: 0, payment_confirmation: 1, in_production: 2, dispatch_in_preparation: 3, already_shipped: 4 }

  

  
end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord

belongs_to :item
belongs_to :order_history

  def subtotal
    tax_included_price * quantity
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!, except: [:top,:about]


  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)


  end

  def edit
    @genre =Genre.find(params[:id])

  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path

  end

  def index
    @genre=Genre.new
    @genres=Genre.all

  end

private

def genre_params
  params.require(:genre).permit(:name)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController


def top
    @order_histories = OrderHistory.all.page(params[:page]).per(10)
    @order_history_details = OrderHistoryDetail.all

end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!, except: [:top,:about]

  def new
     @item = Item.new
     @genres=Genre.all


  end

  def update
    @item =Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)


  end

  def edit
     @item =Item.find(params[:id])
     @genres=Genre.all

  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)


  end

  def index
    @items = Item.all.page(params[:page]).per(10)

  end

  def show
    @item=Item.find(params[:id])



  end

  private

  def item_params

    params.require(:item).permit(:genre_id, :price, :name, :introduction,:is_active, :image)
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
    before_action :authenticate_admin!, except: [:top,:about]

  def show
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def order_histories
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  
  <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>

  <div class="row pt-4">
    <div class="col">
      <%= f.label :ジャンル名 %>
    </div>
    <div class="col">
      <%= f.text_field :name %>
    </div>
    <div class="col">
      <%= f.submit '変更を保存' %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  
  <h1>ジャンル一覧 追加</h1>

  <%= form_with model: @genre, url: '/admin/genres', method: :post do |f| %>
 
  <div class="row pt-4">
    <div class="col">
      <%= f.label :ジャンル名 %>
    </div>
    <div class="col">
        <%= f.text_field :name %>
    </div>
    <div class="col">
      <%= f.submit '新規登録' %>
    </div>
  </div>
  
  <% end %>
  
  <div class="row pt-4">
      <div class="col">
        <table class="table">
          <thead>
            <tr>
              <th>ジャンル</th>
              <th></th>
            </tr>
          </thead>
          
          <% @genres.each do |genres| %>
          
          <tbody>
            <tr>
              <th>
                <%= genres.name %>
              </th>
              <td>
                <%= link_to "編集する", edit_admin_genre_path(genres.id) %>
              </td>
            </tr>
          </tbody>
          
          <% end %>
          
        </table>
    </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  
  <h1>注文履歴一覧</h1>
  
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        
        <% @order_histories.each do |order_history| %>

        <tbody>
          <td>
            <%= link_to admin_order_history_path(order_history.id) do %>
            <%= order_history.created_at %>
            <% end %>
          </td>
          <td><%= order_history.name %></td>
          <td><%= order_history.order_history_details.sum(:quantity) %></td>
          <td></td>
          
        </tbody>
        
        <% end %>
        
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-2 offset-5">
      <%= paginate @order_histories %>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  
  <h1>商品編集</h1>

  <%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>
  
  <div class="row">
    <div class="col text-center">
      商品画像
    </div>
    <div class="col">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      商品名
    </div>
    <div class="col">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      商品説明
    </div>
    <div class="col">
      <%= f.text_area :introduction %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      ジャンル
    </div>
    <div class="col">
      <%= f.collection_select(:genre_id, @genres, :id, :name) %>
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      税抜価格
    </div>
    <div class="col">
      <%= f.number_field :price %>円
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      販売ステータス
    </div>
    <div class="col">
      <%= f.radio_button :is_active,true %>販売中
      <%= f.radio_button :is_active,false %>販売停止中
    </div>
  </div>
  <div class="row pt-3">
    <div class="col text-center">
      <%= f.submit"変更を保存" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-11">
        <h1>商品一覧</h1>
    </div>
    <div class="col-1">
      <%= link_to new_admin_item_path do %>
      <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>購入日時</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @items.each do |item| %>
        <tbody>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
            <%= item.name %>
            <% end %>
          </td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td><%= item.status_text %></td>
        </tbody>
        <% end %>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  
  <h1>商品新規登録</h1>
  
  <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

  <div class="row justify-content-center">
    <div class="col pt-3 text-center">
      商品画像
    </div>
    <div class="col pt-3">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col pt-3 text-center">
      商品名 
    </div>
    <div class="col pt-3">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col pt-3 text-center">
      商品説明
    </div>
    <div class="col pt-3">
      <%= f.text_area :introduction %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col pt-3 text-center">
      ジャンル 
    </div>
    <div class="col pt-3">
      <%= f.collection_select(:genre_id, @genres, :id, :name) %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col pt-3 text-center">
      税抜価格  
    </div>
    <div class="col pt-3">
      <%= f.number_field :price %>円
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col pt-3 text-center">
      販売ステータス
    </div>
    <div class="col pt-3">
      <%= f.radio_button :is_active,true %>販売中
      <%= f.radio_button :is_active,false %>販売停止中
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col pt-3 text-center">
      <%= f.submit"新規登録" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>
<div class="container">
  <div class="row">
    <div class="col">
      <%= image_tag @item.get_image %>
    </div>
    <div class="col container">
      <div class="row pt-3">
        <div class="col">
          商品名
        </div>
        <div class="col">
          <%= @item.name %>
        </div>
      </div>

      <div class="row pt-3">
        
        <div class="col">
          商品説明
        </div>
        <div class="col">
          <%= @item.introduction %>
        </div>
      </div>
        
      <div class="row pt-3">

        <div class="col">
          ジャンル
        </div>
        <div class="col">
          <%= @item.genre.name %>
        </div>
      </div>
      
      <div class="row pt-3">

        <div class="col">
          税込価格（税抜価格）
        </div>
        <div class="col">
          <%= (@item.price*1.10).floor %>
          (<%= @item.price %>)
        </div>
      </div>
      
      <div class="row pt-3">

        <div class="col">
          販売ステータス
        </div>
        <div class="col">
          <%= @item.status_text %>
        </div>
      </div>
    
      <div class="row pt-3">

        <div class="col text-left">
          <%= link_to  "編集する", edit_admin_item_path(@item.id), class:"btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>