config/routes.rb
Rails.application.routes.draw do

 

  # 顧客用
# URL /customers/sign_in ...


# 管理者用
# URL /admin/sign_in ...
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  namespace :admin do
    resources :items, only: [:index, :show, :create, :new, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_histories, only: [:show, :update]
    resources :order_history_details, only: [:update]

    get 'top'=>'homes#top'

  end

  scope module: :public do
    
    root to: "homes#top"
    get "home/about" => "homes#about"
    post 'orders/confirm'=>'orders#confirm'
    get 'orders/complete'=>'orders#complete'
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    patch 'customers/withdraw'=>'customers#withdraw'
    delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :destroy, :create, :update]
    resources :orders, only: [:index, :show, :create, :new]
    resources :addresses, only: [:index, :destroy, :create,  :edit, :update]

  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }


end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :addresses
         has_many :cart_items
         has_many :order_histories
         
  def status_text
     if is_deleted == false
        "有効"
     else
        "退会"
     end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
end

app/models/home.rb
class Home < ApplicationRecord
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many   :cart_items
  has_many   :order_history_details
  belongs_to :genre
  
  has_one_attached :image
  
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [100, 100]).processed
  end
  
  def status_text
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
        
  
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  
  belongs_to :customer
  has_many :order_history_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: { awaiting_payment: 0, payment_confirmation: 1, in_production: 2, dispatch_in_preparation: 3, already_shipped: 4 }

  

  
end

app/models/order_history_detail.rb
class OrderHistoryDetail < ApplicationRecord

belongs_to :item
belongs_to :order_history

  def subtotal
    tax_included_price * quantity
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController


def top
    @order_histories = OrderHistory.all.page(params[:page]).per(10)
    @order_history_details = OrderHistoryDetail.all

end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def order_histories
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
    <% if admin_signed_in? %>
      <li>
        <%= link_to "商品一覧", admin_items_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "会員一覧", admin_customers_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "注文履歴一覧", admin_top_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "ジャンル一覧", admin_genres_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class:"nav-link text-light" %>
      </li>
    <% else %>
    
    <%= render'/layouts/customer_header' %>

    <% end %>

app/views/layouts/_customer_header.html.erb
    <% if customer_signed_in? %>

    ようこそ
    <%= current_customer.last_name %>
    !

      <li>
        <%= link_to "マイページ", customers_path(current_customer.id),class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "カート", cart_items_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class:"nav-link text-light" %>
      </li>
    <% else %>

      <li>
        <%= link_to "About", home_about_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "新規登録", new_customer_registration_path,class:"nav-link text-light" %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path,class:"nav-link text-light" %>
      </li>


    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4cf76a4e78.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

      <% if request.path.match(/\/admin(\/)?/) %>
      <%= render'/layouts/admin_header' %>
      <% else %>
      <%= render'/layouts/customer_header' %>
      <% end %>
        </ul>
       </div>
      </div>
     </nav>

    </header>

    <%= yield %>
  </body>
</html>